# Generated by Django 4.1.7 on 2023-03-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_id', models.CharField(max_length=20)),
                ('site_id', models.CharField(max_length=20)),
                ('date_start', models.DateTimeField(verbose_name='start date')),
                ('date_end', models.DateTimeField(verbose_name='end date')),
                ('filename', models.CharField(max_length=50)),
                ('video_id', models.CharField(max_length=20)),
                ('stratum', models.CharField(max_length=20)),
                ('rotation', models.CharField(max_length=20)),
                ('objects_detected', models.BooleanField()),
                ('max_confidence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(default=0)),
                ('objects_detected', models.BooleanField()),
                ('filename', models.CharField(max_length=255)),
                ('max_confidence', models.IntegerField(default=0)),
                ('video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameratrap.videofile')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.IntegerField(default=0)),
                ('coord_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('confidence', models.IntegerField(default=0)),
                ('pred_class', models.CharField(max_length=255)),
                ('video_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameratrap.videoframe')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ob_date', models.DateTimeField(verbose_name='observation date')),
                ('ob_class', models.CharField(max_length=50)),
                ('ob_order', models.CharField(max_length=50)),
                ('ob_genus', models.CharField(max_length=50)),
                ('ob_species', models.CharField(max_length=50)),
                ('ob_common_name', models.CharField(max_length=255)),
                ('ob_count', models.IntegerField(default=0)),
                ('ob_quality', models.IntegerField(default=0)),
                ('ob_notes', models.CharField(max_length=4000)),
                ('ob_observer', models.CharField(max_length=50)),
                ('ob_observer_2', models.CharField(max_length=50)),
                ('video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameratrap.videofile')),
            ],
        ),
    ]
