# Generated by Django 4.1.7 on 2023-03-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameratrap', '0002_videofile_document_videofile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='ct_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='date_end',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='date_start',
            field=models.DateTimeField(null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='filename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='objects_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='rotation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='site_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='stratum',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='video_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
