# Generated by Django 4.1.7 on 2023-03-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameratrap', '0003_alter_videofile_ct_id_alter_videofile_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='fps_inference',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='fps_video',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='inference_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='max_objects_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='video_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='rotation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='stratum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
