# Generated by Django 4.1.7 on 2023-03-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameratrap', '0004_videofile_fps_inference_videofile_fps_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='video_status',
            field=models.CharField(choices=[('NON', 'None'), ('UPL', 'Uploaded'), ('RDY', 'Ready for Processing'), ('PRO', 'Processed')], default='NON', max_length=3),
        ),
    ]
