# Generated by Django 4.1.7 on 2023-03-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameratrap', '0005_alter_videofile_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='video_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='video_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='fps_inference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='fps_video',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
