# Generated by Django 4.1.7 on 2023-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameratrap', '0007_remove_prediction_coord_x_remove_prediction_coord_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoframe',
            name='objects_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
