# Generated by Django 4.1.7 on 2023-03-21 21:34

import cameratrap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameratrap', '0009_remove_prediction_height_remove_prediction_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='ct_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='document',
            field=models.FileField(null=True, upload_to=cameratrap.models.VideoFile.fn_video_location),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='filename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='site_id',
            field=models.CharField(max_length=20),
        ),
    ]
