# Generated by Django 4.1.7 on 2023-03-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameratrap', '0010_alter_videofile_ct_id_alter_videofile_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoframe',
            name='filename',
            field=models.FileField(upload_to=''),
        ),
    ]
